# -*- coding: utf-8 -*-
"""Crime.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1lX4xsLH-jsZ4JboJUMvEpMI3eJM6Lo
"""

print('SUA PARTICIPAÇÃO NO CRIME\n')
resp = [] 
resp1 = (input(f'\nVocê conhecia a vítima ?\t')).lower()
resp2 = (input(f'\nVocê já trabalhou com a vítima ?\t')).lower()
resp3 = (input(f'\nVocê telefonou para a vítima no dia do crime ?\t')).lower()
resp4 = (input(f'\nVocê esteve no local do crime ?\t')).lower()
print()
suspeito = 'sim'
inocente = 'não'
if (resp[0] and resp[1] and resp[2] and resp[3] == suspeito):
  print('\nvocê é o possível criminoso')
elif (resp[0] and resp[1] and resp[2] == suspeito):
  print('\nVocê é suspeito')
if (resp[0] and resp[1] == suspeito):
  print('\nVocê ainda está sob investigação')
if (resp[0] == suspeito):
  print('\nVocê é o suspeito em não potencial')
else:
  print('\nVocê não é o criminoso')