# -*- coding: utf-8 -*-
"""dicionarios_input.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_4cv_Lm-wt7POma97yC6vijt5dpZB5p
"""

a = {'Seu nome': input('\nDigite seu nome:\t'), 'número da sorte': input('\nQual é o seu número da sorte ?\t')}
b = {'Seu nome': input('\nDigite seu nome:\t'), 'número da sorte': input('\nQual é o seu número da sorte ?\t')}
c = {'Seu nome': input('\nDigite seu nome:\t'), 'número da sorte': input('\nQual é o seu número da sorte?\t')}

print('\nO número favorito de ' + a['Seu nome'] + ' é ' + a['número da sorte'])
print('\nO número favorito de ' + b['Seu nome'] + ' é ' + b['número da sorte'])
print('\nO número favorito de ' + c['Seu nome'] + ' é ' + c['número da sorte'])