# -*- coding: utf-8 -*-
"""Lucro do Enguia.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7u4kwOBqAs2fmKXf4gelyysuinQKMYe

PREÇO E LUCRO DO ENGUIA
"""



icms_comer = 1
icms = 118/100
entrega = 0.51
lucro = 150/100
dólar = 5.44


def preço_enguia_e_lucro():
  preço_do_fornecedor = float(input(f'Insira o preço de compra em Reais: '))
  preço_com_imp = float((preço_do_fornecedor * icms) + entrega)
  print(f'\nO preço de custo do produto és de {preço_com_imp:,.2f} Reais')
  preço_de_venda = float(preço_com_imp * lucro)
  print(f'\nO preço de venda do produto és de {float(preço_com_imp * lucro):,.2f} Reais')
  print(f'\n{preço_de_venda - preço_com_imp:.2f} Reais de lucro por produto')
  
preço_enguia_e_lucro()

