# -*- coding: utf-8 -*-
"""Pizza.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bBmqhAne4rRH58vQJJR9nEmteb78rcT7
"""

#print('Fale três sabores de pizza')
#print()
#pc = []
#p1 = input(f'\nQual o seu sabor favorito de pizza ?\t')
#p2 = input(f'\nQual o seu sabor favorito de pizza ?\t')
#p3 = input(f'\nQual o seu sabor favorito de pizza ?\t')


#p1L = p1.lower()
#p2L = p2.lower()
#p3L = p3.lower()
#pc.append(p1L)
#pc.append(p2L)
#pc.append(p3L)
#print()
#print('\n' + str(pc) + ", eu amo essas pizzas")
#print("\nSão as melhores de todas " + str(pc) +".")