# -*- coding: utf-8 -*-
"""visualização_de_dados.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHeiEpEKurmDfwFkG4Dvk18rxsN4qA7p
"""

from matplotlib import pyplot as plt


frete_unitário = [1, 10 , 20, 30, 40, 50 , 60, 70, 80, 90, 100]

receita_frete = [1.8, 1.8*10, 1.8*20, 1.8*30, 1.8*40, 1.8*50, 1.8*60, 1.8*70, 1.8*80, 1.8*90, 1.8*100]

plt.plot(frete_unitário, receita_frete, color='green', marker='o', linestyle='solid')

plt.title("RECEITA DO FRETE POR UNIDADE VENDIDA")

plt.ylabel("FRETE POR PRODUTO")
plt.xlabel('QUANTIDADE DE PRODUTO')
plt.show()



movies = ["Prejuízo com 10 produtos vendidos", "Receita", "Prejuízo com 50 produtos vendidos", "Receita"]
num_oscars = [-162, 'negativa', -90, 'negativa']
# barras possuem o tamanho padrão de 0.8, então adicionaremos 0.1 às
# coordenadas à esquerda para que cada barra seja centralizada
xs = [i + 0.1 for i, _ in enumerate(movies)]
# as barras do gráfico com as coordenadas x à esquerda [xs], alturas [num_oscars]
plt.bar(xs, num_oscars)
plt.ylabel("Quantidade de produtos vendidos")
plt.title("Lucro e Prejuízo")
# nomeia o eixo x com nomes de filmes na barra central
plt.xticks([i + 0.5 for i, _ in enumerate(movies)], movies)
plt.show()